#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT="$SCRIPT_DIR/generated_presets.h"

# パラメータ数はコアが正本。ここで決め打ちすると、コアにパラメータを足したときに
# ビルドが「範囲外」で止まる（2026-09-05 に id 53/54 で実際に踏んだ）。
MAX_PARAM_ID="$(sed -n 's/^static_assert(kParamCount == \([0-9]*\));.*/\1/p' "$ROOT_DIR/core/src/params.hpp" | head -1)"
if [ -z "$MAX_PARAM_ID" ]; then
    echo "gen_presets.sh: core/src/params.hpp から kParamCount を読めない" >&2
    exit 1
fi
MAX_PARAM_ID=$((MAX_PARAM_ID - 1))

awk -v max_id="$MAX_PARAM_ID" '
function trim(value) {
    sub(/^[[:space:]]+/, "", value)
    sub(/[[:space:]]+$/, "", value)
    return value
}
function basename(path, parts, count) {
    count = split(path, parts, "/")
    return parts[count]
}
function float_literal(value) {
    if (value ~ /^[-+]?[0-9]+$/) value = value ".0"
    return value "f"
}
BEGIN {
    print "// Generated by gen_presets.sh. Do not edit by hand."
    print "#ifndef SYNTH_ENGINE_GENERATED_PRESETS_H"
    print "#define SYNTH_ENGINE_GENERATED_PRESETS_H\n"
    print "struct SynthGeneratedPresetValue {"
    print "    uint32_t id;"
    print "    float value;"
    print "};\n"
    print "struct SynthGeneratedPresetDefinition {"
    print "    const char* name;"
    print "    const SynthGeneratedPresetValue* values;"
    print "    uint32_t valueCount;"
    print "};\n"
}
FNR == 1 {
    if (file_count > 0) print "};\n"
    source = basename(FILENAME)
    ++file_count
    sources[file_count] = source
    if (source == "m0_sine.txt") {
        arrays[file_count] = "kGeneratedInitValues"
        names[file_count] = "Init"
    } else if (source == "m1_unison_saw.txt") {
        arrays[file_count] = "kGeneratedSawLeadValues"
        names[file_count] = "Saw Lead"
    } else if (source == "m1b_filter_sweep.txt") {
        arrays[file_count] = "kGeneratedFilterSweepValues"
        names[file_count] = "Filter Sweep"
    } else if (source == "m1b_wobble.txt") {
        arrays[file_count] = "kGeneratedWobbleValues"
        names[file_count] = "Wobble"
    } else {
        print "gen_presets.sh: unsupported preset " source > "/dev/stderr"
        failed = 1
    }
    delete seen
    print "// Generated from presets/" source "."
    print "static constexpr SynthGeneratedPresetValue " arrays[file_count] "[] = {"
}
{
    line = $0
    sub(/[[:space:]]*#.*/, "", line)
    line = trim(line)
    if (line == "") next
    if (line !~ /^[0-9]+[[:space:]]*=[[:space:]]*[-+]?[0-9]+([.][0-9]*)?([eE][-+]?[0-9]+)?$/) {
        print "gen_presets.sh: invalid line in " FILENAME ": " $0 > "/dev/stderr"
        failed = 1
        next
    }
    split(line, fields, "=")
    id = trim(fields[1]) + 0
    value = trim(fields[2])
    if (id < 0 || id > max_id || seen[id]) {
        print "gen_presets.sh: duplicate or out-of-range id " id " in " FILENAME > "/dev/stderr"
        failed = 1
        next
    }
    seen[id] = 1
    print "    {" id "u, " float_literal(value) "},"
}
END {
    print "};\n"
    if (failed) exit 1
    print "static constexpr SynthGeneratedPresetDefinition kGeneratedPresets[] = {"
    for (preset_index = 1; preset_index <= file_count; ++preset_index) {
        print "    {\"" names[preset_index] "\", " arrays[preset_index] ","
        print "     static_cast<uint32_t>(sizeof(" arrays[preset_index] ") / sizeof(" arrays[preset_index] "[0]))},"
    }
    print "};"
    print "static constexpr uint32_t kGeneratedPresetCount ="
    print "    static_cast<uint32_t>(sizeof(kGeneratedPresets) / sizeof(kGeneratedPresets[0]));"
    print "\n#endif"
}
' \
    "$ROOT_DIR/presets/m0_sine.txt" \
    "$ROOT_DIR/presets/m1_unison_saw.txt" \
    "$ROOT_DIR/presets/m1b_filter_sweep.txt" \
    "$ROOT_DIR/presets/m1b_wobble.txt" > "$OUTPUT"
