// Generated by gen_presets.sh. Do not edit by hand.
#ifndef SYNTH_ENGINE_GENERATED_PRESETS_H
#define SYNTH_ENGINE_GENERATED_PRESETS_H

struct SynthGeneratedPresetValue {
    uint32_t id;
    float value;
};

struct SynthGeneratedPresetDefinition {
    const char* name;
    const SynthGeneratedPresetValue* values;
    uint32_t valueCount;
};

// Generated from presets/m0_sine.txt.
static constexpr SynthGeneratedPresetValue kGeneratedInitValues[] = {
    {0u, 0.0f},
    {1u, 0.0f},
    {2u, 0.8f},
    {3u, 0.005f},
    {4u, 0.1f},
    {5u, 0.8f},
    {6u, 0.2f},
    {7u, 0.2f},
    {8u, 16.0f},
};

// Generated from presets/m1_unison_saw.txt.
static constexpr SynthGeneratedPresetValue kGeneratedSawLeadValues[] = {
    {0u, 1.0f},
    {1u, 0.0f},
    {2u, 0.8f},
    {3u, 0.005f},
    {4u, 0.1f},
    {5u, 0.8f},
    {6u, 0.2f},
    {7u, 0.2f},
    {8u, 16.0f},
    {9u, 4.0f},
    {10u, 12.0f},
    {11u, 0.8f},
    {12u, 0.0f},
    {13u, 0.0f},
    {14u, 0.0f},
    {15u, 0.0f},
    {17u, 0.0f},
    {19u, 0.0f},
    {28u, 0.0f},
    {29u, 0.0f},
    {32u, 0.0f},
};

// Generated from presets/m1b_filter_sweep.txt.
static constexpr SynthGeneratedPresetValue kGeneratedFilterSweepValues[] = {
    {0u, 1.0f},
    {1u, 0.0f},
    {2u, 0.8f},
    {3u, 0.005f},
    {4u, 0.1f},
    {5u, 0.8f},
    {6u, 0.2f},
    {7u, 0.2f},
    {8u, 16.0f},
    {35u, 1.0f},
    {36u, 4.0f},
    {37u, 200.0f},
    {38u, 0.6f},
    {40u, 3.0f},
    {41u, 0.005f},
    {42u, 0.8f},
    {43u, 0.0f},
    {44u, 0.2f},
    {54u, 0.8f},
};

// Generated from presets/m1b_wobble.txt.
static constexpr SynthGeneratedPresetValue kGeneratedWobbleValues[] = {
    {0u, 1.0f},
    {1u, 0.0f},
    {2u, 0.8f},
    {3u, 0.005f},
    {4u, 0.1f},
    {5u, 0.8f},
    {6u, 0.2f},
    {7u, 0.2f},
    {8u, 16.0f},
    {35u, 1.0f},
    {36u, 4.0f},
    {37u, 1000.0f},
    {38u, 0.0f},
    {46u, 5.0f},
    {47u, 0.0f},
    {48u, 0.0f},
    {49u, 3.0f},
};

static constexpr SynthGeneratedPresetDefinition kGeneratedPresets[] = {
    {"Init", kGeneratedInitValues,
     static_cast<uint32_t>(sizeof(kGeneratedInitValues) / sizeof(kGeneratedInitValues[0]))},
    {"Saw Lead", kGeneratedSawLeadValues,
     static_cast<uint32_t>(sizeof(kGeneratedSawLeadValues) / sizeof(kGeneratedSawLeadValues[0]))},
    {"Filter Sweep", kGeneratedFilterSweepValues,
     static_cast<uint32_t>(sizeof(kGeneratedFilterSweepValues) / sizeof(kGeneratedFilterSweepValues[0]))},
    {"Wobble", kGeneratedWobbleValues,
     static_cast<uint32_t>(sizeof(kGeneratedWobbleValues) / sizeof(kGeneratedWobbleValues[0]))},
};
static constexpr uint32_t kGeneratedPresetCount =
    static_cast<uint32_t>(sizeof(kGeneratedPresets) / sizeof(kGeneratedPresets[0]));

#endif
